---
# tasks file for git (CentOS specific)

- name: Install git packages
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ _git_packages_dependencies }}"
  tags:
    - git
