---

- name: Install git package dependencies
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  register: install_git_package_dependencies
  when: _git_package_dependencies is defined
  with_items: _git_package_dependencies
  tags:
    - git
    - apt
    - dependencies
- debug: var=install_git_package_dependencies.stdout_lines

- name: Install git dependencies
  sudo: yes
  apt:
    name: "{{ item.name }}"
    state: present
  register: install_git_dependencies
  when: _git_dependencies is defined
  with_items: _git_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_git_dependencies.stdout_lines