---

- name: Create files
  become: true
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"
  with_items: _git_create_files
  when: _git_create_files is defined
