---
# tasks file for git (Ubuntu specific)

- name: Update package repositories
  sudo: yes
  apt:
    update_cache: True
  tags:
    - git
    - update_cache

- name: Install git packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ _git_packages_dependencies }}"
  tags:
    - git
